[build]
  publish = "."
  command = "echo 'No build step required'"

[build.environment]
  BACKEND_URL = "https://e-voting-backend-6ujp.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://e-voting-backend-6ujp.onrender.com/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"